### ISSUE TITLE
Reimplement the current HTTP tracker using Axum

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#160]
Parent issue: https://github.com/torrust/torrust-tracker/issues/158
It depends on: https://github.com/torrust/torrust-tracker/issues/159

NOTE: We already changed the HTTP API to [Axum](https://github.com/tokio-rs/axum).

### Subtasks

- [x] https://github.com/torrust/torrust-tracker/pull/180. Allow testing of both versions while working on this migration.

Tracker in `public` mode: 

- [x] https://github.com/torrust/torrust-tracker/issues/184
- [x] https://github.com/torrust/torrust-tracker/issues/187
- [x] https://github.com/torrust/torrust-tracker/issues/191

Tracker in `private` mode: 

- [x] https://github.com/torrust/torrust-tracker/issues/195
- [x] https://github.com/torrust/torrust-tracker/issues/196

Tracker in `listed` (whitelisted) mode:

- [x] https://github.com/torrust/torrust-tracker/issues/200
- [x] https://github.com/torrust/torrust-tracker/issues/201

Final subtasks:

- [x] https://github.com/torrust/torrust-tracker/issues/207
- [x] https://github.com/torrust/torrust-tracker/issues/204
- [x] https://github.com/torrust/torrust-tracker/issues/216
- [x] https://github.com/torrust/torrust-tracker/issues/218
- [x] https://github.com/torrust/torrust-tracker/issues/220
- [x] https://github.com/torrust/torrust-tracker/issues/222
- [x] https://github.com/torrust/torrust-tracker/issues/224
- [x] https://github.com/torrust/torrust-tracker/issues/227
- [x] https://github.com/torrust/torrust-tracker/issues/229

Discarded subtask:

- Catch all unhandled errors in handlers and convert them into bencoded generic HTTP tracker response errors. [See this comment](https://github.com/torrust/torrust-tracker/issues/160#issuecomment-1450648824).

**Comment by josecelano** [comment]
I've added the subtasks. I will create a new issue for each subtask keeping this issue to track them.

**Comment by josecelano** [comment]
I'm not going to implement a "catch-all" middleware. The reason I wanted to use it was I was relaying on standard Axum responses; for example, when it can't parse a path params, it returns a 404 BAD REQUEST response with a not bencoded body. As I finally implemented custom extractors, we control all the responses and I think there are no unhandled errors. If we find one we should change it to return the bencoded official error for the HTTP trackers.
