### ISSUE TITLE
Write docs for `torrust_tracker` crate

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#252]
Documentation for the crate: https://docs.rs/torrust-tracker/3.0.0-alpha.1/torrust_tracker/

I've started writing docs for the [torrust-tracker crate](https://crates.io/crates/torrust-tracker).

### Subtasks

- [x] https://github.com/torrust/torrust-tracker/issues/253
- [x] https://github.com/torrust/torrust-tracker/issues/256
- [x] https://github.com/torrust/torrust-tracker/issues/260
- [x] https://github.com/torrust/torrust-tracker/issues/263
- [x] https://github.com/torrust/torrust-tracker/issues/266
- [x] https://github.com/torrust/torrust-tracker/issues/271
- [x] https://github.com/torrust/torrust-tracker/issues/275
- [x] https://github.com/torrust/torrust-tracker/issues/277
- [x] https://github.com/torrust/torrust-tracker/issues/279
- [x] https://github.com/torrust/torrust-tracker/issues/280
- [x] https://github.com/torrust/torrust-tracker/issues/292
- [x] https://github.com/torrust/torrust-tracker/issues/295

**Comment by josecelano** [comment]
Done. It will be available on [docs.rs](https://docs.rs/torrust-tracker/) after releasing [3.0.0-alpha.2](https://github.com/torrust/torrust-tracker/issues/296).
