### ISSUE TITLE
Follow Release Process for `3.0.0-alpha.10`

### ISSUE THREAD

**Issue by da2ce7** [torrust/torrust-tracker#453]
from: [release_process.md](https://github.com/torrust/torrust-tracker/blob/develop/docs/release_process.md)

Comments in the Develop Branch:

- The `develop` branch has the `3.0.0-alpha.10-develop`.
- The version is bumped according to releases, new features, and breaking changes.

Process:

- [x] The `develop` branch is ready for a release.
- [x] [Stage](https://github.com/torrust/torrust-tracker/blob/develop/docs/release_process.md#2-stage-develop-head-for-merging-into-the-main-branch) `develop` HEAD for merging into the `main` branch.
- [x] [Create Release Commit](https://github.com/torrust/torrust-tracker/blob/develop/docs/release_process.md#3-create-release-commit): `release: version 3.0.0-alpha.10`, that removes the `-develop` suffix.
- [x] Create "Release Version `3.0.0-alpha.10`" pull request from from `staging/main` into `main` branch.
- [x] Merge "Release Version `3.0.0-alpha.10`" pull request.
- [x] [Push New Version](https://github.com/torrust/torrust-tracker/blob/develop/docs/release_process.md#5-push-new-version-from-main-head-to-releasesvsemantic-version-branch) from `main` HEAD to `releases/v3.0.0-alpha.10` branch.
- [x] **Check that the deployment is successful!**
- [x] [Create Release Tag](https://github.com/torrust/torrust-tracker/blob/develop/docs/release_process.md#5-push-new-version-from-main-head-to-releasesvsemantic-version-branch) `v3.0.0-alpha.10`.
- [x] Create Release on Github from Tag.
- [x] [Stage](https://github.com/torrust/torrust-tracker/blob/develop/docs/release_process.md#8-stage-main-head-for-merging-into-the-develop-branch) `main` HEAD for merging into the `develop` branch.
- [x] [Create Comment](https://github.com/torrust/torrust-tracker/blob/develop/docs/release_process.md#9-create-comment-that-bumps-next-development-version) that bumps next development version.
- [x] Create "Version `3.0.0-alpha.10` was Released" pull request from from `staging/develop` into `develop` branch.
- [x] Merge "Release Version `3.0.0-alpha.10`" pull request.
