### ISSUE TITLE
Add E2E tests

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#620]
We are not covering the bootstrapping of the app because we use a lot of "spwan". It would be convenient to write some E2E tests for basic features like the following:

- Call the healthcheck endpoints
- Make an announce request using the HTTP tracker
- Make an announce request using the UDP tracker

We can use the docker image like in the [Index](https://github.com/torrust/torrust-index/blob/develop/contrib/dev-tools/container/e2e/sqlite/run-e2e-tests.sh).

### Subtasks

- [x] https://github.com/torrust/torrust-tracker/issues/634
- [x] https://github.com/torrust/torrust-tracker/issues/647
- [x] https://github.com/torrust/torrust-tracker/issues/637

**Comment by josecelano** [comment]
We now run all checks:

- UDP tracker: announce and scrape requests.
- HTTP tracker: announce and scrape requests.
- HealthCheck: request to the health checker endpoint.
