### ISSUE TITLE
Tracker Checker: console command to run tracker checks

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#637]
Parent issue: https://github.com/torrust/torrust-tracker/issues/620

Console command that runs some checks against live running trackers. It would be used for:

- E2E testing.
- Smoke tests after deploying the [live demo](https://index.torrust-demo.com/torrents).

It can be run with the following alternatives:

```console
cargo run --bin tracker_checker -- --config-path "./share/default/config/tracker_checker.json"

TORRUST_CHECKER_CONFIG_PATH="./share/default/config/tracker_checker.json" cargo run --bin tracker_checker

TORRUST_CHECKER_CONFIG=$(cat "./share/default/config/tracker_checker.json") cargo run --bin tracker_checker
```

And you can pass a list of services to check in the configuration:

```json
{
    "udp_trackers": [
        "127.0.0.1:6969"
    ],
    "http_trackers": [
        "http://127.0.0.1:7070"
    ],
    "health_checks": [
        "http://127.0.0.1:1313/health_check"
    ]
}
```

For UDP and HTTP trackers it will make an announce and scrape requests.

### Subtasks

- [x] https://github.com/torrust/torrust-tracker/issues/638
- [x] https://github.com/torrust/torrust-tracker/issues/656
- [x] https://github.com/torrust/torrust-tracker/issues/640
- [x] https://github.com/torrust/torrust-tracker/issues/639

**Comment by josecelano** [comment]
If you want to check the live demo you can use this configuration:

```json
{
    "udp_trackers": [
        "144.126.245.19:6969"
    ],
    "http_trackers": [
        "https://tracker.torrust-demo.com"
    ],
    "health_checks": [
        "https://tracker.torrust-demo.com/api/health_check"
    ]
}
```

```console
cargo run --bin tracker_checker -- --config-path "./tracker_checker.json"
```

**NOTICE**: the `/announce` path is not included.

The current output is:

![image](https://github.com/torrust/torrust-tracker/assets/58816/ab78bdcd-f885-495e-8a07-1ebcd93b1449)

**Comment by josecelano** [comment]
You can also run it without creating the config file with:

```console
TORRUST_CHECKER_CONFIG='{
    "udp_trackers": ["144.126.245.19:6969"],
    "http_trackers": ["https://tracker.torrust-demo.com"],
    "health_checks": ["https://tracker.torrust-demo.com/api/health_check"]
}' cargo run --bin tracker_checker
```

**Comment by josecelano** [comment]
The Tracker Checher does not work with trackers that respond with other fields. For example, this won't work:

```console
TORRUST_CHECKER_CONFIG='{
    "udp_trackers": ["104.21.73.163:80"],
    "http_trackers": ["https://tracker.gbitt.info:443"],
    "health_checks": []
}' cargo run --bin tracker_checker
```

This is the tracker: https://www.gbitt.info/

Probably the announce and scrape responses have more fields than the one we deserialize.

```console
Running checks for trackers ...
UDP trackers ...
✓ - UDP tracker at udp://104.21.73.163:80 is OK (TODO)
HTTP trackers ...
✗ - Announce at https://tracker.gbitt.info/ is failing
thread 'main' panicked at src/shared/bit_torrent/tracker/http/client/responses/scrape.rs:33:46:
provided bytes should be a valid bencoded response: EndOfStream
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by josecelano** [comment]
You can run the checker for the local env or live demo.

### Local dev env

Command:

```console
TORRUST_CHECKER_CONFIG='{
    "udp_trackers": ["127.0.0.1:6969"],
    "http_trackers": ["http://127.0.0.1:7070"],
    "health_checks": ["http://127.0.0.1:1313/health_check"]
}' cargo run --bin tracker_checker
```

Output:

```console
Running checks for trackers ...
UDP trackers ...
✓ - Announce at 127.0.0.1:6969 is OK
✓ - Announce at 127.0.0.1:6969 is OK
HTTP trackers ...
✓ - Announce at http://127.0.0.1:7070/ is OK
✓ - Scrape at http://127.0.0.1:7070/ is OK
Health checks ...
✓ - Health API at http://127.0.0.1:1313/health_check is OK
```

### Live demo

Command:

```console
TORRUST_CHECKER_CONFIG='{
    "udp_trackers": ["144.126.245.19:6969"],
    "http_trackers": ["https://tracker.torrust-demo.com"],
    "health_checks": ["https://tracker.torrust-demo.com/health_check"]
}' cargo run --bin tracker_checker
```

Output:

```console
Running checks for trackers ...
UDP trackers ...
✓ - Announce at 144.126.245.19:6969 is OK
✓ - Announce at 144.126.245.19:6969 is OK
HTTP trackers ...
✓ - Announce at https://tracker.torrust-demo.com/ is OK
✓ - Scrape at https://tracker.torrust-demo.com/ is OK
Health checks ...
✓ - Health API at https://tracker.torrust-demo.com/health_check is OK
```
