### ISSUE TITLE
UDP Tracker Client: add `scrape` request

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#654]
Currently, you can use the UDP Tracker client to make an `announce` request:

```console
cargo run --bin udp_tracker_client 144.126.245.19:6969 9c38422213e30bff212b30c360d26f9a02136422 
    Finished dev [optimized + debuginfo] target(s) in 0.07s
     Running `target/debug/udp_tracker_client '144.126.245.19:6969' 9c38422213e30bff212b30c360d26f9a02136422`
AnnounceIpv4(
    AnnounceResponse {
        transaction_id: TransactionId(
            -888840697,
        ),
        announce_interval: AnnounceInterval(
            300,
        ),
        leechers: NumberOfPeers(
            0,
        ),
        seeders: NumberOfPeers(
            1,
        ),
        peers: [],
    },
)
```

I'm going to add the `scrape` so we can also use it in the [Tracker Checker](https://github.com/torrust/torrust-tracker/issues/640).

```console
cargo run --bin udp_tracker_client announce 144.126.245.19:6969 9c38422213e30bff212b30c360d26f9a02136422 
cargo run --bin udp_tracker_client scrape 144.126.245.19:6969 9c38422213e30bff212b30c360d26f9a02136422 
```

I'm also going to do some refactors.

### Subtasks

- [x] Print JSON instead of debug struct.
- [x] Use `anyhow` and `clap`. See [HTTP Tracker client](https://github.com/torrust/torrust-tracker/blob/develop/src/bin/http_tracker_client.rs).
- [x] `scrape` command.
- [x] Allow using a domain. Currently, it only allows using an IP.

**Comment by josecelano** [comment]
The output:

```console
$ cargo run --bin udp_tracker_client scrape 144.126.245.19:6969 9c38422213e30bff212b30c360d26f9a02136422 | jq
    Finished dev [optimized + debuginfo] target(s) in 0.08s
     Running `target/debug/udp_tracker_client scrape '144.126.245.19:6969' 9c38422213e30bff212b30c360d26f9a02136422`
```

```json
{
  "transaction_id": -888840697,
  "torrent_stats": [
    {
      "seeders": 0,
      "completed": 0,
      "leechers": 0
    }
  ]
}
```
