### ISSUE TITLE
Overhaul clients

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#669]
This is an epic issue for tracking progress with clients.

- [ ] Overhaul **UDP Tracker client**.
   - [x] https://github.com/torrust/torrust-tracker/issues/670
   - [ ] https://github.com/torrust/torrust-tracker/issues/1533
   - [ ] https://github.com/torrust/torrust-tracker/issues/671
   - [ ] https://github.com/torrust/torrust-tracker/issues/1563
- [ ] Overhaul **HTTP Tracker client**.
   - [ ] https://github.com/torrust/torrust-tracker/issues/1532
   - [ ] https://github.com/torrust/torrust-tracker/issues/672
   	 - [x] https://github.com/torrust/torrust-tracker/issues/673
   - [ ] https://github.com/torrust/torrust-tracker/issues/1561
   - [ ] https://github.com/torrust/torrust-tracker/issues/1562
- [ ] Overhaul **Tracker Checker**.
   - [x] https://github.com/torrust/torrust-tracker/issues/674
   - [x] https://github.com/torrust/torrust-tracker/issues/675
   - [x] https://github.com/torrust/torrust-tracker/issues/677
       - [x] https://github.com/torrust/torrust-tracker/issues/682
           - [x] https://github.com/torrust/torrust-tracker/issues/681
       - [x] https://github.com/torrust/torrust-tracker/issues/679
           - [x] https://github.com/torrust/torrust-tracker/issues/680
       - [x] https://github.com/torrust/torrust-tracker/issues/678
   - [x] https://github.com/torrust/torrust-tracker/issues/683
   - [x] https://github.com/torrust/torrust-tracker/issues/676
   - [x] https://github.com/torrust/torrust-tracker/issues/1040
   - [ ] https://github.com/torrust/torrust-tracker/issues/1042
   - [ ] https://github.com/torrust/torrust-tracker/issues/1178
- [x] #767
- [ ] Merge clients into a single **Tracker Client**. See https://github.com/torrust/torrust-tracker/discussions/660
- [ ] https://github.com/torrust/torrust-tracker/issues/1564

**NOTES:** 

- The list order is the recommended order of implementation.
- If you want to contribute to one task but there is no issue yet or want more info feel free to ask for more information.

### Introduction

I've recently added three new tools to the repo. These three console commands can be used for testing and debugging. Since I started working on this project, I've missed tools that can help developers and sys admins detect and fix trackers' problems. The new three console commands are:

#### HTTP Tracker Client

This client allows making `announce` and `scrape` requests to HTTP trackers.

**Announce:**

```console
cargo run --bin http_tracker_client announce http://127.0.0.1:7070 9c38422213e30bff212b30c360d26f9a02136422
```

```json
{
  "complete": 1,
  "incomplete": 0,
  "interval": 120,
  "min interval": 120,
  "peers": []
}
```

**Notice**: all parameters except the `info_hash` are hardcoded. This client is not intended (yet) to be used with a full request from inputs. It's only used for testing so it generates a sample request. It could be changed to accept all parameters as a json object in the future. It depends on [this](https://github.com/torrust/teps/discussions/15).

You could use any browser for the HTTP Tracker Client, but the main advantage is getting the response in JSON instead of Bencoded format.

**Scrape:**

```console
cargo run --bin http_tracker_client scrape http://127.0.0.1:7070 9c38422213e30bff212b30c360d26f9a02136422
```

```json
{
  "9c38422213e30bff212b30c360d26f9a02136422": {
    "complete": 1,
    "downloaded": 0,
    "incomplete": 0
  }
}
```

#### UDP Tracker Client

This client allows making `announce` and `scrape` requests to UDP trackers.

**Announce:**

```console
cargo run --bin udp_tracker_client announce http://127.0.0.1:6969 9c38422213e30bff212b30c360d26f9a02136422
```

```json
{
  "transaction_id": -888840697,
  "announce_interval": 120,
  "leechers": 0,
  "seeders": 1,
  "peers": []
}
```

**Scrape:**

```console
cargo run --bin udp_tracker_client scrape http://127.0.0.1:6969 9c38422213e30bff212b30c360d26f9a02136422
```

```json
{
  "transaction_id": -888840697,
  "torrent_stats": [
    {
      "seeders": 1,
      "completed": 0,
      "leechers": 0
    }
  ]
}
```

**Notice**: this is fully implemented as the only parameter for the `scrape` request is the `info_hash`.

This client is very convenient because there is no easy way to build and send UDP packets. And some BitTorrent clients don't show you the Tracker response. (https://www.biglybt.com/ does it).

#### Tracker Checker

You can use this command to test running services on trackers. It can check:

- UDP trackers: it makes an `announce` and `scrape` request.
- HTP trackers: it makes an `announce` and `scrape` request.
- HTTP endpoints (health check endpoints): it makes a `GET` request to the provided endpoint and checks that the endpoint returns a 200 HTTP status code.

You can run it for the local dev env with:

```console
TORRUST_CHECKER_CONFIG='{
    "udp_trackers": ["127.0.0.1:6969"],
    "http_trackers": ["http://127.0.0.1:7070"],
    "health_checks": ["http://127.0.0.1:1313/health_check"]
}' cargo run --bin tracker_checker
```

or for the live demo with:

```console
TORRUST_CHECKER_CONFIG='{
    "udp_trackers": ["144.126.245.19:6969"],
    "http_trackers": ["https://tracker.torrust-demo.com"],
    "health_checks": ["https://tracker.torrust-demo.com/health_check"]
}' cargo run --bin tracker_checker
```

Output:

```console
Running checks for trackers ...
UDP trackers ...
✓ - Announce at 144.126.245.19:6969 is OK
✓ - Announce at 144.126.245.19:6969 is OK
HTTP trackers ...
✓ - Announce at https://tracker.torrust-demo.com/ is OK
✓ - Scrape at https://tracker.torrust-demo.com/ is OK
Health checks ...
✓ - Health API at https://tracker.torrust-demo.com/health_check is OK
```

### Considerations

This code is still in beta, some parts were moved from testing code to production code. For example the `UdpClient`. That means it's not covered by tests. We should add tests while we implement all these new features. I merged as it is because I wanted to use the Checker in the testing workflow (E2E tests). I wanted to enable this feature asap to avoid regressions when we merge PRs, since a lot of the bootstapping of the app is not covered by unit tests.

**Comment by josecelano** [comment]
[Clients were extracted into a new package](https://github.com/torrust/torrust-tracker/issues/1067), `bittorrent-tracker-client`

**Comment by josecelano** [comment]
This epic has been completed. We only need to clean old binaries once they are not used anymore in the documentation. See https://github.com/torrust/torrust-tracker/issues/1775.
