### ISSUE TITLE
Tracker Checker: gracefully handle timeouts

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#677]
Parent issue: https://github.com/torrust/torrust-tracker/issues/669

Currently, you can run the Tracker Checker with this input:

```console
TORRUST_CHECKER_CONFIG='{
    "udp_trackers": ["127.0.0.1:6969"],
    "http_trackers": ["http://127.0.0.1:7070"],
    "health_checks": ["http://127.0.0.1:1313/health_check"]
}' cargo run --bin tracker_checker
```

In some cases, there could be a missing timeout for network operations and in other cases where there is a timeout, the error is not handled gracefully.

This issue tracks all subtasks related to timeout issues.

### Subtasks

- [x] https://github.com/torrust/torrust-tracker/issues/678
- [x] https://github.com/torrust/torrust-tracker/issues/679
- [x] https://github.com/torrust/torrust-tracker/issues/682

**Comment by josecelano** [comment]
Subtasks finished.
