### ISSUE TITLE
Overhaul logging

### ISSUE THREAD

**Issue by josecelano** [torrust/torrust-tracker#687]
Relates to: https://github.com/torrust/torrust-index/issues/468

Currently, the Tracker logs only include lines like this:

```console
Loading default configuration file: `./share/default/config/tracker.development.sqlite3.toml` ...
2024-02-08T13:54:56.845883372+00:00 [torrust_tracker::bootstrap::logging][INFO] logging initialized.
2024-02-08T13:54:56.850937270+00:00 [UDP Tracker][INFO] Starting on: udp://0.0.0.0:6969
2024-02-08T13:54:56.851174369+00:00 [torrust_tracker::bootstrap::jobs][INFO] TLS not enabled
2024-02-08T13:54:56.852013834+00:00 [HTTP Tracker][INFO] Starting on: http://0.0.0.0:7070
2024-02-08T13:54:56.852030653+00:00 [HTTP Tracker][INFO] Started on: http://0.0.0.0:7070
2024-02-08T13:54:56.852036573+00:00 [torrust_tracker::bootstrap::jobs][INFO] TLS not enabled
2024-02-08T13:54:56.852200992+00:00 [API][INFO] Starting on http://127.0.0.1:1212
2024-02-08T13:54:56.852215812+00:00 [API][INFO] Started on http://127.0.0.1:1212
2024-02-08T13:54:56.852231242+00:00 [Health Check API][INFO] Starting on: http://127.0.0.1:1313
2024-02-08T13:54:56.852250182+00:00 [Health Check API][INFO] Started on: http://127.0.0.1:1313
```

### Subtasks

- [x] https://github.com/torrust/torrust-tracker/issues/600
- [x] https://github.com/torrust/torrust-tracker/issues/696
- [x] https://github.com/torrust/torrust-tracker/issues/700
- [x] https://github.com/torrust/torrust-tracker/issues/697
- [x] https://github.com/torrust/torrust-tracker/issues/698
- [x] https://github.com/torrust/torrust-tracker/issues/704

**Comment by josecelano** [comment]
Please review this PR: https://github.com/torrust/torrust-index/pull/485 before starting to implement this issue. It uses `tower_http::trace::layer` middlewares and it produces an output like this:

```
2024-02-12T18:47:12.390921554+00:00 [API][INFO] request; method=GET uri=/v1/about/license request_id=613cae04-85b5-46c5-a8d8-fe165c79e4e8
2024-02-12T18:47:12.391101653+00:00 [API][INFO] response; latency=0 status=200 OK request_id=613cae04-85b5-46c5-a8d8-fe165c79e4e8
```
